# ahora imagínate una página web que edita este yaml

#   # Networking
#   
#   ## Pla de VLANs amb FXOLN
#   
#   Estats de les VLANs:
#   
#   - Provisional: en fase de disseny, pendent d'aprovar disseny, pendent de demanar a FXOLN
#   - Assignada: aplicada per XFOLN; preparada per utilitzar
#   - En producció: en ús

vlan map:
  - id: 90
    type: fxoln
    code: gfilan
    subnet: 10.38.140.224/27
    notes: guifi LAN (accés des de guifi)
  - id: 91
    type: fxoln
    code: gfiptp1
    subnet: 172.25.38.208/29
    notes: troncal per wifi amb Alambra
  - id: 92
    type: fxoln
    code: gfiptp2
    subnet: 172.25.45.8/29
    notes: troncal per wifi amb Ermita
  - id: 93
    type: fxoln
    code: gfiptp3
    subnet: 172.25.40.64/30
    notes: troncal per wifi amb Can Bruixa
  - id: 10
    type: fxoln
    code: gfiptp4
    subnet: 172.25.34.48/30
    notes: troncal amb FXOLN (BGP de 10.0.0.0/8)
  - id: 102
    type: fxoln
    code: ix
    subnet: 10.253.4.0/22
    notes: Internet Exchange amb FXOLN
  - id: 94
    type: fxoln
    code: inetsrv
    subnet: 192.168.94.0/24
    notes: servers accessibles des d'Internet
  - id: 95
    type: fxoln
    code: rproxy
    subnet: 192.168.95.0/24
    notes: concentrador de HTTPS (reverse proxy, etc)
  - id: 96
    type: fxoln
    code: pve
    subnet: 192.168.96.0/24
    notes: tràfic clúster proxmox
  - id: 97
    type: fxoln
    code: gfs
    subnet: 192.168.97.0/24
    notes: tràfic clúster gluster
  - id: 98
    type: fxoln
    code: ctrl
    subnet: 192.168.98.0/24
    notes: control, gestió
 - id: 128
     type: fxoln
     code: operador
     notes: la dona FXOLN, no sabem per què serveix
 - id: 127
     type: internal
     code: ipmi
     subnet: 192.168.127.0/24
     notes: VLAN interna de IPMI

trax1:
  vlan:
  - id: 96
    vmbr0: 192.168.96.11/24
  - id: 97
    vmbr0: 192.168.97.11/24
  - id: 98
    vmbr0: 192.168.98.11/24
    gateway: 192.168.98.13
  - id: 127 # vlan interna, connectada a mikrotik/trax3
    ipmi: 192.168.127.11/24
trax2:
  vlan:
  - id: 96
    vmbr0: 192.168.96.12/24
  - id: 97
    vmbr0: 192.168.97.12/24
  - id: 98
    vmbr0: 192.168.98.12/24
    gateway: 192.168.98.13
  - id: 127 # vlan interna, connectada a mikrotik/trax3
    ipmi: 192.168.127.12/24
mikrotik: # provisional
  vlan:
  - id: 102
    vmbr0: 10.253.4.28/22 # TODO: canviar nom de vmbr0
    gateway: 10.253.4.21
  - id: 127
    vmbr0: 192.168.127.13/24
trax3:
  loopback: 109.69.10.96
  vlan:
  - id: 96
    vmbr0: 192.168.96.13/24
  - id: 97
    vmbr0: 192.168.97.13/24
  - id: 98
    vmbr0: 192.168.98.13/24
    gateway: 192.168.98.13
  - id: 102 # pendent de confirmar amb FXOLN
    vmbr0: 10.253.4.29/22
    gateway: 10.253.4.21
  - id: 127 # vlan interna, connectada a mikrotik/trax3
    ipmi: 192.168.127.13/24


### VMs?

# ## Gateways
# 
# De situació temporal a situació definitiva
# 
# trax1 i trax2 surten per Mikrotik a través de VLAN98
# 
# després ho faran per atom (trax3) a travé de la mateixa VLAN98
# 
# la justificació d'això és que no trobem eficient que vagi de la màquina host a la màquina virtual de routing per tornar a sortir al host
